import { NextRequest, NextResponse } from "next/server"
import { auth } from "@/auth"
import { getAuditById, getIssuesByAudit } from "@/db/repositories/audits"
import { getSiteById } from "@/db/repositories/sites"

/** GET /api/v1/audits/:id/action-plan-md — export action plan as Markdown */
export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth()
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { id } = await params
  const audit = await getAuditById(id)
  if (!audit) return NextResponse.json({ error: "Not found" }, { status: 404 })

  const site = await getSiteById(audit.siteId, session.user.id)
  if (!site) return NextResponse.json({ error: "Forbidden" }, { status: 403 })

  const issues = await getIssuesByAudit(id, { limit: 50 })
  const ranked = [...issues].sort((a, b) => {
    if (a.revenueImpactRank == null && b.revenueImpactRank == null) return 0
    if (a.revenueImpactRank == null) return 1
    if (b.revenueImpactRank == null) return -1
    return a.revenueImpactRank - b.revenueImpactRank
  })

  const date = audit.completedAt
    ? new Date(audit.completedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })

  const sevLabel = (s: string) => s === "critical" ? "🔴 Critical" : s === "warning" ? "🟡 Warning" : "🔵 Info"

  const lines: string[] = [
    `# SEO Action Plan — ${site.displayName ?? site.domain}`,
    ``,
    `**Date:** ${date}  `,
    `**Health Score:** ${audit.healthScore ?? "N/A"}/100  `,
    `**Pages Crawled:** ${audit.pagesCount ?? 0}  `,
    `**Issues Found:** ${ranked.length}  `,
    ``,
    `---`,
    ``,
    `## Issues Ranked by Revenue Impact`,
    ``,
  ]

  for (const [i, issue] of ranked.entries()) {
    const fixed = issue.isFixed ? " ✅ Fixed" : ""
    lines.push(`### ${i + 1}. ${issue.title}${fixed}`)
    lines.push(``)
    lines.push(`**Severity:** ${sevLabel(issue.severity)} | **Category:** ${issue.category.replace("_", " ")} | **Pages affected:** ${issue.affectedCount}`)
    lines.push(``)
    lines.push(issue.description)
    lines.push(``)
    if (issue.fixInstructions) {
      lines.push(`**How to fix:**`)
      lines.push(``)
      lines.push(issue.fixInstructions)
      lines.push(``)
    }
    if (Array.isArray(issue.affectedUrls) && (issue.affectedUrls as string[]).length > 0) {
      lines.push(`**Affected URLs:**`)
      lines.push(``)
      const urls = (issue.affectedUrls as string[]).slice(0, 5)
      for (const url of urls) lines.push(`- ${url}`)
      lines.push(``)
    }
    lines.push(`---`)
    lines.push(``)
  }

  lines.push(`*Generated by RankIQ — ${new Date().toISOString().slice(0, 10)}*`)

  const md = lines.join("\n")
  const filename = `rankiq-action-plan-${site.domain}-${new Date().toISOString().slice(0, 10)}.md`

  return new NextResponse(md, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  })
}
